name: client-test
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  
jobs:
  Test:    
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2  
      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
      
      - name: Create VENV for the tap
        run: |
          python3 -m venv tap-dealcloud
      
      - name: Install the tap
        run: |
          source tap-dealcloud/bin/activate
          python tap-dealcloud/setup.py install          
        
      - name: Fetch config files from the secrets
        env:
          TAP_CONFIG: ${{ secrets.TAP_CONFIG }}          
        run: |
          echo $TAP_CONFIG > tap-dealcloud/client_config.json          
        
      - name: 'Unit Tests'          
        run: |                    
          python -m unittest discover tests
